baseurl = "https://canardpresse.reviews/"
title = "Canard presse"
author = "Angela Giesen & Hans Kruse"
copyright = "Copyright © 2014–2019, Angela Giesen & Hans Kruse  all rights reserved."
canonifyurls = true
paginate = 3
theme = "silhouette-hugo"

pygmentsUseClasses=true

#disqusShortname = ""
#googleAnalytics = ""

[params]
author = "Angela Giesen & Hans Kruse"
introDescription = "Eet smakelijk"
contentSharing = "Feel free to share this content non commercially, Attribution-NonCommercial-ShareAlike"

[social]
# instagram = ""
# linkedin = ""
# twitter = ""

