baseURL = "https://canardpresse.reviews"
languageCode = "en-uk"
title = "Canard Presse - restaurant reviews"
theme = "ananke" 

MetaDataFormat = "yaml"
DefaultContentLanguage = "en-uk"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Food is love, Food is passion but an evening at a restaurant will cost you quickly a week of groceries for a small family"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  featured_image = "/images/Deventer_skyline.jpg"
  recent_posts_number = 6
